language: python
python:
  - "2.7"
env:
  - DJANGO=1.5.5 DB=sqlite3
install:
  - pip install -r requirements/production.txt --use-mirrors
script:
  - cd transfers
  - export DJANGO_SETTINGS_MODULE=pymg.test_settings
  - python manage.py syncdb --noinput
  - python manage.py migrate --all
  - python manage.py test
